<?php
function holy_form_sites_node_form_alter(&$form, &$form_state){

		$form['#attached']['css'][] = drupal_get_path("module", "holy").'/sites_node_form.css';
//		drupal_set_message(drupal_get_path("module", "holy").'/sites_node_form.css');
}

function holy_form_alter(&$form, &$form_state, $form_id){

	$form['#attached']['css'][] = drupal_get_path("module", "holy").'/node_form.css';
	//		drupal_set_message(drupal_get_path("module", "holy").'/sites_node_form.css');
}
