<?php
function holy_form_sites_node_form_alter(&$form, &$form_state){
		$form['#attached']['css'][] = drupal_get_path("module", "holy").'/sites_node_form.css';
}
function holy_form_lectures_publications_node_form_alter(&$form, &$form_state){
		$form['#attached']['css'][] = drupal_get_path("module", "holy").'/lectures_publications_node_form.css';
//		drupal_set_message(drupal_get_path("module", "holy").'/sites_node_form.css');

}		
function holy_form_alter(&$form, &$form_state, $form_id){

	$form['#attached']['css'][] = drupal_get_path("module", "holy").'/node_form.css';
	//		drupal_set_message(drupal_get_path("module", "holy").'/sites_node_form.css');
}
function holy_node_update($node){
    variable_set("last_modified", date('d/m/Y'));
}
function holy_user_insert(&$edit, $account, $category) {
	$role_name = 'editor'; // The name of the role to add.
	if ($role = user_role_load_by_name($role_name)) {
	 user_multiple_role_edit(array($account->uid), 'add_role', $role->rid);
	}
}
